#!/usr/bin/python3

import subprocess 
import os
import sys
import pickle
from argparse import ArgumentParser

def loadItems(filename):
    if os.path.exists(filename):
        with open(filename,"rb") as f:
            items=pickle.load(f)
    else:
        items={}
    return items

def saveItems(items,filename):
    with open(filename,"wb") as f:
        pickle.dump(items,f)

if __name__=="__main__":
    filename=os.path.expanduser("~/.refitems")
    items=loadItems(filename)

    argparser=ArgumentParser()
    argparser.add_argument(
        '--add',
        dest='add',
        nargs=2,
        metavar=('key','filename'),
        help='add a key into list.'
        )
    argparser.add_argument(
        '--del',
        dest='_del',
        nargs=1,
        metavar='key',
        help='delete a key.'
        )
    argparser.add_argument(
        '--list',
        dest='list',
        action='store_true',
        help='show list of keys.'
        )
    argparser.add_argument(
        'key',
        nargs='?',
        help='show documet corresponding to key.'
        )
    args=argparser.parse_args()

    try:
        if args.add != None:
            items[args.add[0]]={"objname":os.path.abspath(args.add[1])}
            saveItems(items,filename)
        elif args._del != None:
            del items[args._del[0]]
            saveItems(items,filename)
        elif args.list:
            for key in items:
                print(key)
        elif args.key != None:
            subprocess.run(["less",items[args.key]["objname"]])
        else:
            argparser.print_help()
    except KeyError as e:
        print("No items matches key %s"%(str(e)))
